[files]
extend-exclude = [
    "tests",
    "testdata",
    "dist-workspace.toml",
    "crates/parse/src/lexer/unicode_chars.rs",
]

[default.extend-words]
ket = "ket"

[default]
extend-ignore-identifiers-re = ["[0-9A-fa-f]{20,}"]
